### PR TITLE
FISH-7076 : Malformed SQL Query caused by EclipseLink with Table per …

### PR DESCRIPTION
**Pull request by luiseufrasio**
…class inheritance and secondary tables

(cherry picked from commit 1097b7733899b8f2907826a3d17cedca76f7d18a)

### CODE REVIEW

**Review by Pandrex247 — COMMENTED** [review]
Looking at eclipselink-4.0.0-M3.payara-maintenance I see the following commits applied on top of the "base" eclipselink-4.0.0-M3 which aren't being included here:
* https://github.com/payara/patched-src-eclipselink/commit/7ebf78f5cc091a98cb2507bdce2ffae6018f07f2
* https://github.com/payara/patched-src-eclipselink/commit/c202dfc0c8eff3cdae29f005001f038fc53e8987
* https://github.com/payara/patched-src-eclipselink/commit/7c682fbce3e372123f69ab84c6a83cdbfededd99
* https://github.com/payara/patched-src-eclipselink/commit/960624e594935ff4f9634a9db69f89e1b0173ca2
* https://github.com/payara/patched-src-eclipselink/commit/905f48525de96c630b1e247de161b412c233f403
* https://github.com/payara/patched-src-eclipselink/commit/63d5fdd665cb213b951c3db82bcc49aa415dad3c

Are none of these required anymore?

**Comment by luiseufrasio** [comment]
These are already done in 4.0.1:
https://github.com/payara/patched-src-eclipselink/commit/7ebf78f5cc091a98cb2507bdce2ffae6018f07f2
https://github.com/payara/patched-src-eclipselink/commit/c202dfc0c8eff3cdae29f005001f038fc53e8987

**Comment by luiseufrasio** [comment]
jenkins test please

**Review by arieki — APPROVED** [review]
Approved, all commit from eclipselink-4.0.0-M3.payara-maintenance mentioned by @Pandrex247   https://github.com/payara/patched-src-eclipselink/pull/26#pullrequestreview-1369882499 has been included

**Pull request merged**
